### ISSUE TITLE
Drop support for PostgreSQL < 9.2 ?

### ISSUE THREAD

**Issue by strk** [linz/linz-postgresql-functions#5]
Is support for PostgreSQL 9.0 still needed ?

I'm asking because Travis can only test from 9.1 to 9.5 when using `ubuntu precise` target and from 9.2 to 9.6 when using `ubuntu trusty`.

Also note that PostgreSQL 9.0 reached EOL in September 2015, and 9.1 reached it in September 2016.
REF: https://www.postgresql.org/support/versioning/

**Comment by strk** [comment]
4a6e870 changes the Makefile to rely more on PGXS. Travis is now testing from 9.2 to 9.6 and it passes the install and enable tests.

**Comment by palmerj** [comment]
No it's no longer required. We upgraded to 9.3 about a year ago at LINZ.
